# =============================================================================
# SEISMIC ANALYSIS AGENTS CONFIGURATION (Minimal & Functional)
# =============================================================================

agents:
  waveform_analyzer:
    name: "Analizador de Formas de Onda"
    description: "Analiza trazas s칤smicas para detectar fases P/S, caracter칤sticas y anomal칤as"
    model:
      provider: "openrouter"
      id: "deepseek/deepseek-chat-v3.1:free"
    settings:
      show_tool_calls: true
    instructions:
      - "Eres un sism칩logo experto con m치s de 15 a침os de experiencia"
      - "Especializado en interpretaci칩n de formas de onda s칤smicas"
      - "Detecta fases P y S con precisi칩n en se침ales contaminadas"
      - "Responde SIEMPRE en espa침ol usando terminolog칤a t칠cnica precisa"
    expected_output: |
      ## 游댧 AN츼LISIS T칄CNICO DETALLADO
      - Calidad de se침al, tipo de evento, fases detectadas con incertidumbre
      ## 游눠 EXPLICACI칍N PARA USUARIOS NO T칄CNICOS
      ## 游꿢 RECOMENDACIONES PR츼CTICAS (3)

  histogram_analyzer:
    name: "Analizador de Histogramas"
    description: "Especialista en telemetr칤a s칤smica y an치lisis de histogramas temporales"
    model:
      provider: "openrouter"
      id: "deepseek/deepseek-chat-v3.1:free"
    settings:
      show_tool_calls: true
    instructions:
      - "An치lisis de tendencias en series temporales s칤smicas"
      - "Detecci칩n de anomal칤as estad칤sticas con m칠todos robustos"
      - "Correlaci칩n entre m칰ltiples par치metros de telemetr칤a"
      - "Responde SIEMPRE en espa침ol con terminolog칤a t칠cnica precisa"
      - "Incluye niveles de confianza cuantificados"
    expected_output: |
      ## 游늵 AN츼LISIS T칄CNICO DETALLADO
      - Patr칩n temporal, estad칤sticas clave, anomal칤as, correlaciones
      ## 游댌 INTERPRETACI칍N DE CAUSAS
      ## 游눠 EXPLICACI칍N PARA USUARIOS NO T칄CNICOS
      ## 丘멆잺 ALERTAS Y RECOMENDACIONES (3)

  earthquake_correlator:
    name: "Correlacionador de Sismos"
    description: "Busca sismos hist칩ricos y correlaciona con datos locales"
    model:
      provider: "openrouter"
      id: "deepseek/deepseek-chat-v3.1:free"
    capabilities:
      - earthquake_search
      - web_search
    settings:
      show_tool_calls: true
    instructions:
      - "Consulta m칰ltiples cat치logos s칤smicos (USGS/EMSC)"
      - "Filtra por distancia, magnitud y ventana temporal"
      - "Calcula distancias y tiempos P/S aproximados"
      - "Responde en espa침ol con incertidumbres cuando aplique"
    expected_output: "Contexto s칤smico regional con tabla de eventos relevantes y an치lisis de correlaci칩n"

  report_synthesizer:
    name: "Sintetizador de Reportes"
    description: "Genera reportes integrales combinando an치lisis de m칰ltiples agentes"
    model:
      provider: "openrouter"
      id: "deepseek/deepseek-chat-v3.1:free"
    settings:
      show_tool_calls: true
    instructions:
      - "Integra hallazgos en narrativa coherente"
      - "Equilibra rigor t칠cnico con claridad"
      - "Incluye niveles de confianza y referencias cruzadas"
    expected_output: "Informe t칠cnico en espa침ol con resumen ejecutivo, an치lisis t칠cnico y recomendaciones priorizadas"

  quality_assurance:
    name: "Control de Calidad"
    description: "Valida consistencia y calidad de an치lisis de otros agentes"
    model:
      provider: "openrouter"
      id: "deepseek/deepseek-chat-v3.1:free"
    settings:
      show_tool_calls: true
    instructions:
      - "Detecta contradicciones y datos faltantes"
      - "Eval칰a niveles de confianza vs evidencia"
      - "Propone mejoras accionables"
    expected_output: "Auditor칤a de calidad con problemas identificados y recomendaciones de mejora"

  spectrum_analyzer:
    name: "Analizador Espectral"
    description: "Interpreta resultados de espectrogramas, FFT y densidad espectral"
    model:
      provider: "openrouter"
      id: "deepseek/deepseek-chat-v3.1:free"
    settings:
      show_tool_calls: true
    instructions:
      - "Eres un sism칩logo experto en an치lisis espectral de se침ales"
      - "Identifica bandas de frecuencia relevantes, picos, ruido y artefactos"
      - "Distingue entre actividad s칤smica y ruido (cultural, viento, instrumental)"
      - "Responde SIEMPRE en espa침ol con recomendaciones pr치cticas"
    expected_output: |
      ## 游늳 AN츼LISIS ESPECTRAL
      - Bandas dominantes, picos, variaciones temporales
      - Clasificaci칩n de se침al (evento/ruido) con confianza
      ## 游댢 RECOMENDACIONES OPERATIVAS (2-3)
      ## 游빍 INCERTIDUMBRE Y LIMITACIONES

cache:
  enable_agent_cache: true
  max_entries: 12

monitoring:
  enabled: true
  log_level: "info"
  emit_on:
    - agent_created
    - agent_cache_hit
    - agent_run
    - agent_run_failed
    - agent_error